apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-svc-deployment
spec:
  selector:
    matchLabels:
      app: account-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: account-svc
        env: test
    spec:
      containers:
        - name: account-svc
          image: com.fcant/account-svc:v0.0.1
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: account-svc
spec:
  selector:
    app: account-svc
    env: test
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082