apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-svc-deployment
spec:
  selector:
    matchLabels:
      app: company-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: company-svc
        env: test
    spec:
      containers:
        - name: company-svc
          image: com.fcant/company-svc:v0.0.1
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: company-svc
spec:
  selector:
    app: company-svc
    env: test
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081