server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffjoy_company
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: comapny-svc
eureka:
  client:
    service-url:
      # 将网关注册到注册中心
      defaultZone: http://127.0.0.1:8761/eureka/